# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        autowire: true
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.security.login_form_authenticator:
      class: AppBundle\Security\LoginFormAuthenticator
      autowire: true

    app.security.acl_provider:
          class: AppBundle\Security\ACLSecurityProvider
          autowire: true

    app.security.authentication_failure_event_listener:
      class: AppBundle\Security\AuthenticationFailureListener
      autowire: true
      tags:
      - {name: kernel.event_subscriber}

    security.user_checker:
        class: AppBundle\Security\UserChecker
        arguments: [ "app.security.login_form_authenticator:", "" ]

    app.twig.menu_extension:
        class: AppBundle\Twig\MenuExtension
        arguments:
            - '@knp_menu.helper'
            - '@knp_menu.matcher'
        tags:
            - { name: twig.extension }

    app.acl_voter:
            class: AppBundle\Security\ACLVoter
            autowire: true
            tags:
                - { name: security.voter }
            # small performance boost
            public: false